prompt 'Droping the current tables...'
drop table COLLECTAUDIT_BAK_orig;
drop table TBL_ENUM_DEFINE_orig;
drop table TBL_ENUM_TYPE_orig;
drop table TBL_MED_ADUIT_ERROR_LOG_orig;
drop table TBL_MED_ADUIT_MISSINGFILE_orig;
drop table TBL_MED_ADUIT_TEMP_FILESEQ_orig;
drop table TBL_MED_ALARM_orig;
drop table TBL_MED_ALARM_FIX_SUGGEST_orig;
drop table TBL_MED_CLASS_PROPERTIES_orig;
drop table TBL_MED_CLASS_RELATION_orig;
drop table TBL_MED_CLASS_TYPE_orig;
drop table TBL_MED_COLLECTAUDIT_orig;
drop table TBL_MED_COMPONENTAUDIT_orig;
drop table TBL_MED_DETAIL_LOG_orig;
drop table TBL_MED_DISPATCHAUDIT_orig;
drop table TBL_MED_ERROR_LOG_orig;
drop table TBL_MED_FILEAUDIT_orig;
drop table TBL_MED_FILENAME_INFO_orig;
drop table TBL_MED_FUNCTION_orig;
drop table TBL_MED_G6_SERVICECODE_orig;
drop table TBL_MED_JOB_HISTORY_orig;
drop table TBL_MED_MAP_DICT_orig;
drop table TBL_MED_OBJECT_orig;
drop table TBL_MED_OBJECT_ACC_orig;
drop table TBL_MED_OBJECT_PROPERTIES_orig;
drop table TBL_MED_OBJECT_PROPERTIES_ACC_orig;
drop table TBL_MED_OBJECT_RELATION_orig;
drop table TBL_MED_OBJECT_RELATION_ACC_orig;
drop table TBL_MED_OBJECT_USERLOG_orig;
drop table TBL_MED_PARAM_orig;
drop table TBL_MED_PAYFLAG_INFO_orig;
drop table TBL_MED_PRODUDURE_EXELOG_orig;
drop table TBL_MED_RULE_CONTENT_orig;
drop table TBL_MED_RULE_CONTENT_ACC_orig;
drop table TBL_MED_SEGINFO_orig;
drop table TBL_MED_STAT_ERRORCODE_orig;
drop table TBL_MED_STAT_FILEINFO_orig;
drop table TBL_MED_STAT_LOG_orig;
drop table TBL_MED_USER_ID_orig;
drop table TBL_MED_WEB_BUSINESSSYSTEM_orig;
drop table TBL_MED_WEB_CDRTYPESTAT_orig;
drop table TBL_MED_WEB_COLLECTFILESTAT_orig;
drop table TBL_MED_WEB_COLLECTINFO_orig;
drop table TBL_MED_WEB_FILENAME_orig;
drop table TBL_MED_WEB_SAMSUNG_orig;
drop table TBL_MED_WRITEFILE_orig;
drop table TBL_MICE_WEB_CONNECT_orig;

prompt 'restoring the backup tables'

alter table COLLECTAUDIT_BAK_orig rename to COLLECTAUDIT_BAK;
alter table TBL_ENUM_DEFINE_orig rename to TBL_ENUM_DEFINE;
alter table TBL_ENUM_TYPE_orig rename to TBL_ENUM_TYPE;
alter table TBL_MED_ADUIT_ERROR_LOG_orig rename to TBL_MED_ADUIT_ERROR_LOG;
alter table TBL_MED_ADUIT_MISSINGFILE_orig rename to TBL_MED_ADUIT_MISSINGFILE;
alter table TBL_MED_ADUIT_TEMP_FILESEQ_orig rename to TBL_MED_ADUIT_TEMP_FILESEQ;
alter table TBL_MED_ALARM_orig rename to TBL_MED_ALARM;
alter table TBL_MED_ALARM_FIX_SUGGEST_orig rename to TBL_MED_ALARM_FIX_SUGGEST;
alter table TBL_MED_CLASS_PROPERTIES_orig rename to TBL_MED_CLASS_PROPERTIES;
alter table TBL_MED_CLASS_RELATION_orig rename to TBL_MED_CLASS_RELATION;
alter table TBL_MED_CLASS_TYPE_orig rename to TBL_MED_CLASS_TYPE;
alter table TBL_MED_COLLECTAUDIT_orig rename to TBL_MED_COLLECTAUDIT;
alter table TBL_MED_COMPONENTAUDIT_orig rename to TBL_MED_COMPONENTAUDIT;
alter table TBL_MED_DETAIL_LOG_orig rename to TBL_MED_DETAIL_LOG;
alter table TBL_MED_DISPATCHAUDIT_orig rename to TBL_MED_DISPATCHAUDIT;
alter table TBL_MED_ERROR_LOG_orig rename to TBL_MED_ERROR_LOG;
alter table TBL_MED_FILEAUDIT_orig rename to TBL_MED_FILEAUDIT;
alter table TBL_MED_FILENAME_INFO_orig rename to TBL_MED_FILENAME_INFO;
alter table TBL_MED_FUNCTION_orig rename to TBL_MED_FUNCTION;
alter table TBL_MED_G6_SERVICECODE_orig rename to TBL_MED_G6_SERVICECODE;
alter table TBL_MED_JOB_HISTORY_orig rename to TBL_MED_JOB_HISTORY;
alter table TBL_MED_MAP_DICT_orig rename to TBL_MED_MAP_DICT;
alter table TBL_MED_OBJECT_orig rename to TBL_MED_OBJECT;
alter table TBL_MED_OBJECT_ACC_orig rename to TBL_MED_OBJECT_ACC;
alter table TBL_MED_OBJECT_PROPERTIES_orig rename to TBL_MED_OBJECT_PROPERTIES;
alter table TBL_MED_OBJECT_PROPERTIES_ACC_orig rename to TBL_MED_OBJECT_PROPERTIES_ACC;
alter table TBL_MED_OBJECT_RELATION_orig rename to TBL_MED_OBJECT_RELATION;
alter table TBL_MED_OBJECT_RELATION_ACC_orig rename to TBL_MED_OBJECT_RELATION_ACC;
alter table TBL_MED_OBJECT_USERLOG_orig rename to TBL_MED_OBJECT_USERLOG;
alter table TBL_MED_PARAM_orig rename to TBL_MED_PARAM;
alter table TBL_MED_PAYFLAG_INFO_orig rename to TBL_MED_PAYFLAG_INFO;
alter table TBL_MED_PRODUDURE_EXELOG_orig rename to TBL_MED_PRODUDURE_EXELOG;
alter table TBL_MED_RULE_CONTENT_orig rename to TBL_MED_RULE_CONTENT;
alter table TBL_MED_RULE_CONTENT_ACC_orig rename to TBL_MED_RULE_CONTENT_ACC;
alter table TBL_MED_SEGINFO_orig rename to TBL_MED_SEGINFO;
alter table TBL_MED_STAT_ERRORCODE_orig rename to TBL_MED_STAT_ERRORCODE;
alter table TBL_MED_STAT_FILEINFO_orig rename to TBL_MED_STAT_FILEINFO;
alter table TBL_MED_STAT_LOG_orig rename to TBL_MED_STAT_LOG;
alter table TBL_MED_USER_ID_orig rename to TBL_MED_USER_ID;
alter table TBL_MED_WEB_BUSINESSSYSTEM_orig rename to TBL_MED_WEB_BUSINESSSYSTEM;
alter table TBL_MED_WEB_CDRTYPESTAT_orig rename to TBL_MED_WEB_CDRTYPESTAT;
alter table TBL_MED_WEB_COLLECTFILESTAT_orig rename to TBL_MED_WEB_COLLECTFILESTAT;
alter table TBL_MED_WEB_COLLECTINFO_orig rename to TBL_MED_WEB_COLLECTINFO;
alter table TBL_MED_WEB_FILENAME_orig rename to TBL_MED_WEB_FILENAME;
alter table TBL_MED_WEB_SAMSUNG_orig rename to TBL_MED_WEB_SAMSUNG;
alter table TBL_MED_WRITEFILE_orig rename to TBL_MED_WRITEFILE;
alter table TBL_MICE_WEB_CONNECT_orig rename to TBL_MICE_WEB_CONNECT;

